services:

    amulen_payment.gateway.button.nps:
        class: Amulen\PaymentBundle\Service\Nps\NpsPaymentButtonGateway
        arguments:
          - "@router"
          - "@amulen.dashboard.service.setting"
          - "@soap.client.factory"

    amulen_payment.collect_setting_options_subscriber:
        class: Amulen\PaymentBundle\Event\CollectSettingOptionsSubscriber
        arguments: ['@translator']
        tags:
            - { name: kernel.event_subscriber }

    soap.client.factory:
        class: Amulen\PaymentBundle\Service\Nps\SoapClientFactory
        arguments:
          - "@logger"
          - "@amulen.dashboard.service.setting"
          
    amulen.dashboard.service.setting:
        class: Amulen\PaymentBundle\Mock\DashboardServiceSetting
        arguments:
            - "@service_container"
            
            
    amulen.shop.repository.order:
        class: Amulen\PaymentBundle\Mock\ShopRepositoryOrder
        
        
        
    amulen_payment.gateway.button.mp:
        class: Amulen\PaymentBundle\Service\Mp\MpPaymentButtonGateway
        arguments:
          - "@router"
          - "@logger"
          - "@event_dispatcher"
          - "@amulen.dashboard.service.setting"
          - "@amulen.shop.repository.order"

      
    amulen_payment.gateway.button.paypal:
        class: Amulen\PaymentBundle\Service\Paypal\PaypalPaymentButtonGateway
        arguments:
          - "@router"
          - "@service_container"
          - "@logger"
          - "@amulen.dashboard.service.setting"
       
    amulen_payment.gateway.subscription.button.paypal:
        class: Amulen\PaymentBundle\Service\Paypal\PaypalSubscriptionButtonGateway
        arguments:
          - "@router"
          - "@service_container"
          - "@logger"
          - "@amulen.dashboard.service.setting"
          
    #Factory
    amulen_payment.payment.info.builder.factory:
        class: Amulen\PaymentBundle\Model\Factory\PaymentInfoBuilderFactory
        arguments:
          - "@service_container"

    amulen_payment.payment.button.gateway.factory:
        class: Amulen\PaymentBundle\Model\Factory\PaymentButtonGatewayFactory
        arguments:
          - "@service_container"
          

    #Builder
    amulen_payment.builder.mp:
        class: Amulen\PaymentBundle\Model\Gateway\Mp\PaymentInfoBuilder

    amulen_payment.builder.nps:
        class: Amulen\PaymentBundle\Model\Gateway\Nps\PaymentInfoBuilder
   
    amulen_payment.builder.paypal:
        class: Amulen\PaymentBundle\Model\Gateway\Paypal\PaymentInfoBuilder
    
    amulen_payment.subscription.builder.paypal:
        class: Amulen\PaymentBundle\Model\Gateway\Paypal\SubscriptionInfoBuilder
        
    amulen_payment.paypal.service:
        class: Amulen\PaymentBundle\Service\Paypal\PaypalService
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"
          - "@router"
          - "@logger"
          - "@amulen.dashboard.service.setting"
          