services:

    amulen_payment.gateway.button.nps:
        class: Amulen\PaymentBundle\Service\Nps\NpsPaymentButtonGateway
        arguments:
          - "@router"
          - "@amulen.dashboard.service.setting"

    amulen_payment.collect_setting_options_subscriber:
        class: Amulen\PaymentBundle\Event\CollectSettingOptionsSubscriber
        arguments: ['@translator']
        tags:
            - { name: kernel.event_subscriber }