services:

    amulen_payment.gateway.button.nps:
        class: Amulen\PaymentBundle\Service\Nps\NpsPaymentButtonGateway
        arguments:
          - "@router"
          - "@amulen.dashboard.service.setting"
          - "@soap.client.factory"

    amulen_payment.collect_setting_options_subscriber:
        class: Amulen\PaymentBundle\Event\CollectSettingOptionsSubscriber
        arguments: ['@translator']
        tags:
            - { name: kernel.event_subscriber }

    soap.client.factory:
        class: Amulen\PaymentBundle\Service\Nps\SoapClientFactory
        arguments:
          - "@logger"
          - "@amulen.dashboard.service.setting"

    amulen_payment.gateway.button.mp:
        class: Amulen\PaymentBundle\Service\Mp\MpPaymentButtonGateway
        arguments:
          - "@router"
          - "@logger"
          - "@event_dispatcher"
          - "@amulen.dashboard.service.setting"
          - "@amulen.shop.repository.order"

    #Factory
    amulen_payment.payment.info.builder.factory:
        class: Amulen\PaymentBundle\Model\Factory\PaymentInfoBuilderFactory
        arguments:
          - "@service_container"

    amulen_payment.payment.button.gateway.factory:
        class: Amulen\PaymentBundle\Model\Factory\PaymentButtonGatewayFactory
        arguments:
          - "@service_container"

    #Builder
    amulen_payment.builder.mp:
        class: Amulen\PaymentBundle\Model\Gateway\Mp\PaymentInfoBuilder

    amulen_payment.builder.nps:
        class: Amulen\PaymentBundle\Model\Gateway\Nps\PaymentInfoBuilder